[package]
name = "sled-rpc"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
dirs = "2.0.1"
sled = "0.24.1"
serde_json = "1.0.39"
jsonrpc-core = "12.0.0"
jsonrpc-http-server = "12.0.0"